---
name: Filter-Heredoc
version: 0.01
author:
  - 'Bertil Kronlund <bkron at cpan.org>'
abstract: Search and filter embedded here documents
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  Test::More: 0
requires:
  perl: 5.01
configure_requires:
  Module::Build: 0.340201
provides:
  Filter::Heredoc:
    file: lib/Filter/Heredoc.pm
    version: 0.01
  Filter::Heredoc::App:
    file: lib/Filter/Heredoc/App.pm
    version: 0.01
  Filter::Heredoc::Rule:
    file: lib/Filter/Heredoc/Rule.pm
    version: 0.01
generated_by: Module::Build version 0.340201
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
