---
abstract: 'Search and filter embedded here documents'
author:
  - 'Bertil Kronlund <bkron at cpan.org>'
build_requires:
  Test::More: '0'
configure_requires:
  Module::Build: '0.42'
dynamic_config: 1
generated_by: 'Module::Build version 0.4205, CPAN::Meta::Converter version 2.143240'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Filter-Heredoc
provides:
  Filter::Heredoc:
    file: lib/Filter/Heredoc.pm
    version: 0.03_01
  Filter::Heredoc::App:
    file: lib/Filter/Heredoc/App.pm
    version: 0.03_01
  Filter::Heredoc::Rule:
    file: lib/Filter/Heredoc/Rule.pm
    version: 0.03_01
requires:
  perl: '5.01'
resources:
  license: http://dev.perl.org/licenses/
version: 0.03_01
